[package]
name = "precompile-utils"
version = "0.2.0"
authors = ["PureStake"]
edition = "2021"
description = "Utils to write EVM precompiles."

[dependencies]
ethereum = { version = "0.11.1", default-features = false, features = ["with-serde"] }
ethereum-types = { version = "0.12", default-features = false }
evm = { version = "0.33.1", default-features = false, features = ["with-serde"] }
log = "0.4.14"
num_enum = { version = "0.5.6", default-features = false }
precompile-utils-macro = { path = "macro" }
sha3 = { version = "0.10", default-features = false }
